language: java
jdk:
  - oraclejdk7

before_install:
  - chmod +x gradlew

script:
  - "./gradlew clean desktop:jar"

after_success:
  "echo HUGE SUCCESS"

notifications:
  email:
    on_success: [never]